/* Generated By:JJTree: Do not edit this line. ASTAplatissement_postfixe.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTAplatissement_postfixe extends SimpleNode {
  public ASTAplatissement_postfixe(int id) {
    super(id);
  }

  public ASTAplatissement_postfixe(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ba86169abf6ce48c6f32809155a7294c (do not edit this line) */
