/* Generated By:JJTree: Do not edit this line. ASTAplatissement_prefixe.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTAplatissement_prefixe extends SimpleNode {
  public ASTAplatissement_prefixe(int id) {
    super(id);
  }

  public ASTAplatissement_prefixe(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c6e478ba08b1c7b22d540a6f2c0289f1 (do not edit this line) */
