/* Generated By:JJTree: Do not edit this line. ASTArbre_binaire_en_extension.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTArbre_binaire_en_extension extends SimpleNode {
  public ASTArbre_binaire_en_extension(int id) {
    super(id);
  }

  public ASTArbre_binaire_en_extension(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=04e89373ca0e8cfb9f7f0d25685589d2 (do not edit this line) */
