/* Generated By:JJTree: Do not edit this line. ASTAbstractVariables.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTAbstractVariables extends SimpleNode {
  public ASTAbstractVariables(int id) {
    super(id);
  }

  public ASTAbstractVariables(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=aa0e7c6a8049e5f3db00543130622900 (do not edit this line) */
