/* Generated By:JJTree: Do not edit this line. ASTAplatissement_infixe.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTAplatissement_infixe extends SimpleNode {
  public ASTAplatissement_infixe(int id) {
    super(id);
  }

  public ASTAplatissement_infixe(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2af20fef63814fac9f807f5df7a19b0f (do not edit this line) */
