/* Generated By:JJTree: Do not edit this line. ASTBijection_totale.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTBijection_totale extends SimpleNode {
  public ASTBijection_totale(int id) {
    super(id);
  }

  public ASTBijection_totale(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ea8339a3c61447d463491191d72e9c26 (do not edit this line) */
