/* Generated By:JJTree: Do not edit this line. ASTBoolean_Lit.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTBoolean_Lit extends SimpleNode {
  public ASTBoolean_Lit(int id) {
    super(id);
  }

  public ASTBoolean_Lit(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ab1d1f99282a0af4b6cb0ccb7b88ad01 (do not edit this line) */
