/* Generated By:JJTree: Do not edit this line. ASTConstruction_d_ensembles.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTConstruction_d_ensembles extends SimpleNode {
  public ASTConstruction_d_ensembles(int id) {
    super(id);
  }

  public ASTConstruction_d_ensembles(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=df19f1e509fe772d6f6c135ed3b2dfe1 (do not edit this line) */
