/* Generated By:JJTree: Do not edit this line. ASTConstruction_de_suites.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTConstruction_de_suites extends SimpleNode {
  public ASTConstruction_de_suites(int id) {
    super(id);
  }

  public ASTConstruction_de_suites(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4a0904e6199d76f260d2d9e2696801ea (do not edit this line) */
