/* Generated By:JJTree: Do not edit this line. ASTChamp_de_record.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTChamp_de_record extends SimpleNode {
  public ASTChamp_de_record(int id) {
    super(id);
  }

  public ASTChamp_de_record(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7ad21ec425839c833b0932ebb90a1b73 (do not edit this line) */
