/* Generated By:JJTree: Do not edit this line. ASTConstruction_de_fonctions.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTConstruction_de_fonctions extends SimpleNode {
  public ASTConstruction_de_fonctions(int id) {
    super(id);
  }

  public ASTConstruction_de_fonctions(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=875d19370e29c4d754c2d71f54373aa2 (do not edit this line) */
