/* Generated By:JJTree: Do not edit this line. ASTConcreteConstants.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTConcreteConstants extends SimpleNode {
  public ASTConcreteConstants(int id) {
    super(id);
  }

  public ASTConcreteConstants(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=cd1cbc4fc5386662ca964959c87950f2 (do not edit this line) */
