/* Generated By:JJTree: Do not edit this line. ASTExpr_tableau.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTExpr_tableau extends SimpleNode {
  public ASTExpr_tableau(int id) {
    super(id);
  }

  public ASTExpr_tableau(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=453e525d58c98e6221ca4a7fcc509b5d (do not edit this line) */
