/* Generated By:JJTree: Do not edit this line. ASTExpression_de_couples.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTExpression_de_couples extends SimpleNode {
  public ASTExpression_de_couples(int id) {
    super(id);
  }

  public ASTExpression_de_couples(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=23db7ae8428710c6f0dca0be72d805a0 (do not edit this line) */
