/* Generated By:JJTree: Do not edit this line. ASTExpression_primaire.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTExpression_primaire extends SimpleNode {
  public ASTExpression_primaire(int id) {
    super(id);
  }

  public ASTExpression_primaire(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=303c015d36abd89a92ecb2a11895edef (do not edit this line) */
