/* Generated By:JJTree: Do not edit this line. ASTEnsemble_entier.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTEnsemble_entier extends SimpleNode {
  public ASTEnsemble_entier(int id) {
    super(id);
  }

  public ASTEnsemble_entier(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c817342a81889ff794b3594ea9d40ac6 (do not edit this line) */
