/* Generated By:JJTree: Do not edit this line. ASTEvaluation_fonction.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTEvaluation_fonction extends SimpleNode {
  public ASTEvaluation_fonction(int id) {
    super(id);
  }

  public ASTEvaluation_fonction(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d62b2481fceb0a1dde948e460add16ce (do not edit this line) */
