/* Generated By:JJTree: Do not edit this line. ASTEnsemble_simple.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTEnsemble_simple extends SimpleNode {
  public ASTEnsemble_simple(int id) {
    super(id);
  }

  public ASTEnsemble_simple(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c9e79fc93dfd3b7b84b41b527ff06e73 (do not edit this line) */
