/* Generated By:JJTree: Do not edit this line. ASTExpression_d_arbres.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTExpression_d_arbres extends SimpleNode {
  public ASTExpression_d_arbres(int id) {
    super(id);
  }

  public ASTExpression_d_arbres(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3f123988a349ca18e611ebdc081dad43 (do not edit this line) */
