/* Generated By:JJTree: Do not edit this line. ASTExpression_de_suites.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTExpression_de_suites extends SimpleNode {
  public ASTExpression_de_suites(int id) {
    super(id);
  }

  public ASTExpression_de_suites(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e2a3920cdcc6dfc93ce965353d02b5e6 (do not edit this line) */
