/* Generated By:JJTree: Do not edit this line. ASTExpression_de_records.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTExpression_de_records extends SimpleNode {
  public ASTExpression_de_records(int id) {
    super(id);
  }

  public ASTExpression_de_records(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b4976728bf39e52a6c072f3e656765f4 (do not edit this line) */
