/* Generated By:JJTree: Do not edit this line. ASTExpression_de_fonctions.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTExpression_de_fonctions extends SimpleNode {
  public ASTExpression_de_fonctions(int id) {
    super(id);
  }

  public ASTExpression_de_fonctions(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=69654d79de5717a7e0e71be306c06e37 (do not edit this line) */
