/* Generated By:JJTree: Do not edit this line. ASTEnteteOperation.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTEnteteOperation extends SimpleNode {
  public ASTEnteteOperation(int id) {
    super(id);
  }

  public ASTEnteteOperation(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6a8b49d664cff5477f1c43480a44e0ab (do not edit this line) */
