/* Generated By:JJTree: Do not edit this line. ASTEnsemble_booleen.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTEnsemble_booleen extends SimpleNode {
  public ASTEnsemble_booleen(int id) {
    super(id);
  }

  public ASTEnsemble_booleen(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f285f9bba0b6c0ed00fef9b5af985eb6 (do not edit this line) */
