/* Generated By:JJTree: Do not edit this line. ASTEns_comprehension.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTEns_comprehension extends SimpleNode {
  public ASTEns_comprehension(int id) {
    super(id);
  }

  public ASTEns_comprehension(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=dcbd42c97419225b53e5ef9132767c15 (do not edit this line) */
