/* Generated By:JJTree: Do not edit this line. ASTExpression_de_suites.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTExpression_de_suites extends SimpleNode {
  public ASTExpression_de_suites(int id) {
    super(id);
  }

  public ASTExpression_de_suites(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=49839be0d3c239f380407d7638455b46 (do not edit this line) */
