/* Generated By:JJTree: Do not edit this line. ASTEnteteOperation.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public class ASTEnteteOperation extends SimpleNode {
	private String ident;

	public ASTEnteteOperation(int id) {
		super(id);
	}

	public ASTEnteteOperation(ParserB p, int id) {
		super(p, id);
	}

	public void setIdent(String i) {
		ident = i;
	}

	public String getIdent() {
		return ident;
	}

	public String toString() {
		return "Identifiant : " + ident;
	}

	/** Accept the visitor. **/
	public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

		return visitor.visit(this, data);
	}
}
/*
 * JavaCC - OriginalChecksum=57dcc440c20b50a8a6de1c197766486b (do not edit this
 * line)
 */
