/* Generated By:JJTree: Do not edit this line. ASTEnsemble_chaine.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTEnsemble_chaine extends SimpleNode {
  public ASTEnsemble_chaine(int id) {
    super(id);
  }

  public ASTEnsemble_chaine(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b71742fc2a7943771aa067d356bdcd74 (do not edit this line) */
