/* Generated By:JJTree: Do not edit this line. ASTExpression_d_ensembles.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTExpression_d_ensembles extends SimpleNode {
  public ASTExpression_d_ensembles(int id) {
    super(id);
  }

  public ASTExpression_d_ensembles(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9215bde8760944760667270c42bbf9d4 (do not edit this line) */
