/* Generated By:JJTree: Do not edit this line. ASTExpression_de_relations.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTExpression_de_relations extends SimpleNode {
  public ASTExpression_de_relations(int id) {
    super(id);
  }

  public ASTExpression_de_relations(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=49ac522522d7f68b072ab5c3fbae4d92 (do not edit this line) */
