/* Generated By:JJTree: Do not edit this line. ASTFonction_totale.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTFonction_totale extends SimpleNode {
  public ASTFonction_totale(int id) {
    super(id);
  }

  public ASTFonction_totale(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a06a8642a79249aadcb68ed235c0dd14 (do not edit this line) */
