/* Generated By:JJTree: Do not edit this line. ASTFils_arbre.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTFils_arbre extends SimpleNode {
  public ASTFils_arbre(int id) {
    super(id);
  }

  public ASTFils_arbre(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6862174624b0d134e19cdbb4fc0d2483 (do not edit this line) */
