/* Generated By:JJTree: Do not edit this line. ASTFermeture.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTFermeture extends SimpleNode {
  public ASTFermeture(int id) {
    super(id);
  }

  public ASTFermeture(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=17e2fd40ddd19f0be0655bcbd2d7fd4e (do not edit this line) */
