/* Generated By:JJTree: Do not edit this line. ASTIntersection_generalisee.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTIntersection_generalisee extends SimpleNode {
  public ASTIntersection_generalisee(int id) {
    super(id);
  }

  public ASTIntersection_generalisee(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6f8b6e57d4fd071636a7c1426e984f36 (do not edit this line) */
