/* Generated By:JJTree: Do not edit this line. ASTInstruction_assertion.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTInstruction_assertion extends SimpleNode {
  public ASTInstruction_assertion(int id) {
    super(id);
  }

  public ASTInstruction_assertion(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6bf1a651f45cf85e4d8ccb3256bb70a4 (do not edit this line) */
