/* Generated By:JJTree: Do not edit this line. ASTInstruction_cas.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTInstruction_cas extends SimpleNode {
  public ASTInstruction_cas(int id) {
    super(id);
  }

  public ASTInstruction_cas(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6e99b51727795c29b36b1a40ce07cfa6 (do not edit this line) */
