/* Generated By:JJTree: Do not edit this line. ASTIntersection_quantifiee.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTIntersection_quantifiee extends SimpleNode {
  public ASTIntersection_quantifiee(int id) {
    super(id);
  }

  public ASTIntersection_quantifiee(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8444f91aa7568677a36eafdb82a1e703 (do not edit this line) */
