/* Generated By:JJTree: Do not edit this line. ASTInsertion_tete.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTInsertion_tete extends SimpleNode {
  public ASTInsertion_tete(int id) {
    super(id);
  }

  public ASTInsertion_tete(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4e50ba1db53297f68ff23c60a18d2b57 (do not edit this line) */
