/* Generated By:JJTree: Do not edit this line. ASTInstruction_sequence.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTInstruction_sequence extends SimpleNode {
  public ASTInstruction_sequence(int id) {
    super(id);
  }

  public ASTInstruction_sequence(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=75d2f165ee99dfa3e9ffd0359977b87e (do not edit this line) */
