/* Generated By:JJTree: Do not edit this line. ASTInstruction_appel_operation.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTInstruction_appel_operation extends SimpleNode {
  public ASTInstruction_appel_operation(int id) {
    super(id);
  }

  public ASTInstruction_appel_operation(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=58c0a7b00cd054ee13db5c1a99d4835e (do not edit this line) */
