/* Generated By:JJTree: Do not edit this line. ASTInstruction_sequence.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTInstruction_sequence extends SimpleNode {
  public ASTInstruction_sequence(int id) {
    super(id);
  }

  public ASTInstruction_sequence(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e4a348039c80552f502b68501fd04876 (do not edit this line) */
