/* Generated By:JJTree: Do not edit this line. ASTInitialisation.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTInitialisation extends SimpleNode {
  public ASTInitialisation(int id) {
    super(id);
  }

  public ASTInitialisation(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d3affe6ec0507a139c70d0c8e54d6dd5 (do not edit this line) */
