/* Generated By:JJTree: Do not edit this line. ASTInstruction_bloc.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTInstruction_bloc extends SimpleNode {
  public ASTInstruction_bloc(int id) {
    super(id);
  }

  public ASTInstruction_bloc(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=64ae6bbd94f0ef8e3dce45d8dbabc8bc (do not edit this line) */
