/* Generated By:JJTree: Do not edit this line. ASTInstruciton_variable_locale.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTInstruciton_variable_locale extends SimpleNode {
  public ASTInstruciton_variable_locale(int id) {
    super(id);
  }

  public ASTInstruciton_variable_locale(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4e19d7f37a0bd9e028beac593756b80f (do not edit this line) */
