/* Generated By:JJTree: Do not edit this line. ASTInjection_partielle.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTInjection_partielle extends SimpleNode {
  public ASTInjection_partielle(int id) {
    super(id);
  }

  public ASTInjection_partielle(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e5ce66618e6a6bdfce94a261a6ea0417 (do not edit this line) */
