/* Generated By:JJTree: Do not edit this line. ASTInverse_suite.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTInverse_suite extends SimpleNode {
  public ASTInverse_suite(int id) {
    super(id);
  }

  public ASTInverse_suite(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c13e0aa4c88b84336b9a25ee54fe39e9 (do not edit this line) */
