/* Generated By:JJTree: Do not edit this line. ASTPredicat_Inclusion.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTPredicat_Inclusion extends SimpleNode {
  public ASTPredicat_Inclusion(int id) {
    super(id);
  }

  public ASTPredicat_Inclusion(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=261c210c8d3a7f6ffc66d802d638f748 (do not edit this line) */
