/* Generated By:JJTree: Do not edit this line. ASTPredicat_Insclusion_Stricte.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTPredicat_Insclusion_Stricte extends SimpleNode {
  public ASTPredicat_Insclusion_Stricte(int id) {
    super(id);
  }

  public ASTPredicat_Insclusion_Stricte(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a004bf9e72552af8ff51a5916f53954d (do not edit this line) */
