/* Generated By:JJTree: Do not edit this line. ASTPredicat_Appartenance.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTPredicat_Appartenance extends SimpleNode {
  public ASTPredicat_Appartenance(int id) {
    super(id);
  }

  public ASTPredicat_Appartenance(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3eab4aca04202b300d0d9bdfe60ef4fe (do not edit this line) */
