/* Generated By:JJTree: Do not edit this line. ASTPremiere_projection.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTPremiere_projection extends SimpleNode {
  public ASTPremiere_projection(int id) {
    super(id);
  }

  public ASTPremiere_projection(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ccdb1d4539e9b9e7925ad9f4ebaf66c6 (do not edit this line) */
