/* Generated By:JJTree: Do not edit this line. ASTPredicat_Conjonction.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTPredicat_Conjonction extends SimpleNode {
  public ASTPredicat_Conjonction(int id) {
    super(id);
  }

  public ASTPredicat_Conjonction(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5bda5597b21c26a8d9f2d6bcbcb6cbb8 (do not edit this line) */
