/* Generated By:JJTree: Do not edit this line. ASTPredicat_Non_Inclusion_Stricte.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTPredicat_Non_Inclusion_Stricte extends SimpleNode {
  public ASTPredicat_Non_Inclusion_Stricte(int id) {
    super(id);
  }

  public ASTPredicat_Non_Inclusion_Stricte(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d02f4cf7da1ae73d6cac80af774ccd1a (do not edit this line) */
