/* Generated By:JJTree: Do not edit this line. ASTPredicat_Existentiel.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTPredicat_Existentiel extends SimpleNode {
  public ASTPredicat_Existentiel(int id) {
    super(id);
  }

  public ASTPredicat_Existentiel(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b318c2baf2edef508e8f13cd6a4f00b2 (do not edit this line) */
