/* Generated By:JJTree: Do not edit this line. ASTProduit_parallele.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTProduit_parallele extends SimpleNode {
  public ASTProduit_parallele(int id) {
    super(id);
  }

  public ASTProduit_parallele(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=57baf413060b3cb5d8284b6ed72ce362 (do not edit this line) */
