/* Generated By:JJTree: Do not edit this line. ASTPredicat_Strictement_Inferieur.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTPredicat_Strictement_Inferieur extends SimpleNode {
  public ASTPredicat_Strictement_Inferieur(int id) {
    super(id);
  }

  public ASTPredicat_Strictement_Inferieur(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=400233f6fb8dae236644ba8de1db05b6 (do not edit this line) */
