/* Generated By:JJTree: Do not edit this line. ASTPredicat_Disjonction.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTPredicat_Disjonction extends SimpleNode {
  public ASTPredicat_Disjonction(int id) {
    super(id);
  }

  public ASTPredicat_Disjonction(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=248bf5f97059cef4fc2ec39f98b8876c (do not edit this line) */
