/* Generated By:JJTree: Do not edit this line. ASTPredicat_parenthese.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTPredicat_parenthese extends SimpleNode {
  public ASTPredicat_parenthese(int id) {
    super(id);
  }

  public ASTPredicat_parenthese(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9227379382d870f10699cb9c42684027 (do not edit this line) */
