/* Generated By:JJTree: Do not edit this line. ASTPredicat_Egalite.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTPredicat_Egalite extends SimpleNode {
  public ASTPredicat_Egalite(int id) {
    super(id);
  }

  public ASTPredicat_Egalite(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d83c572f8f80c71dbb38aa6b0327531e (do not edit this line) */
