/* Generated By:JJTree: Do not edit this line. ASTPredicat_Strictement_Superieur.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTPredicat_Strictement_Superieur extends SimpleNode {
  public ASTPredicat_Strictement_Superieur(int id) {
    super(id);
  }

  public ASTPredicat_Strictement_Superieur(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ad2ac57aa39538994fb36371d40e9aae (do not edit this line) */
