/* Generated By:JJTree: Do not edit this line. ASTPredicat_Negation.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTPredicat_Negation extends SimpleNode {
  public ASTPredicat_Negation(int id) {
    super(id);
  }

  public ASTPredicat_Negation(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4e0ab3121dd360c5f896a769e8861d47 (do not edit this line) */
