/* Generated By:JJTree: Do not edit this line. ASTPredicat_Universel.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTPredicat_Universel extends SimpleNode {
  public ASTPredicat_Universel(int id) {
    super(id);
  }

  public ASTPredicat_Universel(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e3d32dcec2186cce06e07c8c3c0d7f80 (do not edit this line) */
