/* Generated By:JJTree: Do not edit this line. ASTRestriction_domaine.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTRestriction_domaine extends SimpleNode {
  public ASTRestriction_domaine(int id) {
    super(id);
  }

  public ASTRestriction_domaine(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3d31b1e48c29708de421e8bae381d175 (do not edit this line) */
