/* Generated By:JJTree: Do not edit this line. ASTRestriction_codomaine.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTRestriction_codomaine extends SimpleNode {
  public ASTRestriction_codomaine(int id) {
    super(id);
  }

  public ASTRestriction_codomaine(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9988792f193dd349480bbb1bdcbf4af3 (do not edit this line) */
