/* Generated By:JJTree: Do not edit this line. ASTRestriction_Domaine.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTRestriction_Domaine extends SimpleNode {
  public ASTRestriction_Domaine(int id) {
    super(id);
  }

  public ASTRestriction_Domaine(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=bc2d95d7c85296fcd3ba090a1d5c11c6 (do not edit this line) */
