/* Generated By:JJTree: Do not edit this line. ASTRecord_en_extension.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTRecord_en_extension extends SimpleNode {
  public ASTRecord_en_extension(int id) {
    super(id);
  }

  public ASTRecord_en_extension(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9b78a2c6ae680b9400487c9a8ae7d4ae (do not edit this line) */
