/* Generated By:JJTree: Do not edit this line. ASTRestriction_tete.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTRestriction_tete extends SimpleNode {
  public ASTRestriction_tete(int id) {
    super(id);
  }

  public ASTRestriction_tete(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ebc714723493835673d8a221f57a8c2b (do not edit this line) */
