/* Generated By:JJTree: Do not edit this line. ASTSubstitution_identite.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTSubstitution_identite extends SimpleNode {
  public ASTSubstitution_identite(int id) {
    super(id);
  }

  public ASTSubstitution_identite(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=04825d95f658be578bdbdff3395574f2 (do not edit this line) */
