/* Generated By:JJTree: Do not edit this line. ASTSous_arbre_droit.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTSous_arbre_droit extends SimpleNode {
  public ASTSous_arbre_droit(int id) {
    super(id);
  }

  public ASTSous_arbre_droit(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ff7700e988ce0db134bca1330f5f31ee (do not edit this line) */
