/* Generated By:JJTree: Do not edit this line. ASTSuite_extension.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTSuite_extension extends SimpleNode {
  public ASTSuite_extension(int id) {
    super(id);
  }

  public ASTSuite_extension(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=769b8767772feac3009f4df5553fd609 (do not edit this line) */
