/* Generated By:JJTree: Do not edit this line. ASTSubstitution_definition_locale.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTSubstitution_definition_locale extends SimpleNode {
  public ASTSubstitution_definition_locale(int id) {
    super(id);
  }

  public ASTSubstitution_definition_locale(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f536a8cb77b0fa9bd8b735eb131728db (do not edit this line) */
