/* Generated By:JJTree: Do not edit this line. ASTSuites_non_vide.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTSuites_non_vide extends SimpleNode {
  public ASTSuites_non_vide(int id) {
    super(id);
  }

  public ASTSuites_non_vide(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0f7b185e089738bb95f173cea80abed4 (do not edit this line) */
