/* Generated By:JJTree: Do not edit this line. ASTSoustraction_codomaine.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTSoustraction_codomaine extends SimpleNode {
  public ASTSoustraction_codomaine(int id) {
    super(id);
  }

  public ASTSoustraction_codomaine(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=107cd8c5aba79a05400bff86a484de2c (do not edit this line) */
