/* Generated By:JJTree: Do not edit this line. ASTSous_ensembles_finis.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTSous_ensembles_finis extends SimpleNode {
  public ASTSous_ensembles_finis(int id) {
    super(id);
  }

  public ASTSous_ensembles_finis(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9f80a28849150f00ffaae48a730f7a57 (do not edit this line) */
