/* Generated By:JJTree: Do not edit this line. ASTSous_ensembles.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTSous_ensembles extends SimpleNode {
  public ASTSous_ensembles(int id) {
    super(id);
  }

  public ASTSous_ensembles(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=63971a543d2829f1393524cbe38e022a (do not edit this line) */
