/* Generated By:JJTree: Do not edit this line. ASTSubstitution_devient_elt_de.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTSubstitution_devient_elt_de extends SimpleNode {
  public ASTSubstitution_devient_elt_de(int id) {
    super(id);
  }

  public ASTSubstitution_devient_elt_de(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2a04429b2d0f26b705ed255842077a7e (do not edit this line) */
