/* Generated By:JJTree: Do not edit this line. ASTSuite_vide.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTSuite_vide extends SimpleNode {
  public ASTSuite_vide(int id) {
    super(id);
  }

  public ASTSuite_vide(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d0a2a2fe4b7c97607299aaa5fddb1c37 (do not edit this line) */
