/* Generated By:JJTree: Do not edit this line. ASTSous_ensembles.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTSous_ensembles extends SimpleNode {
  public ASTSous_ensembles(int id) {
    super(id);
  }

  public ASTSous_ensembles(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=bffcd279d4b2483e1bf34b1d9859ffae (do not edit this line) */
