/* Generated By:JJTree: Do not edit this line. ASTSymetrie_arbre.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTSymetrie_arbre extends SimpleNode {
  public ASTSymetrie_arbre(int id) {
    super(id);
  }

  public ASTSymetrie_arbre(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=994e1693459be876e38489ac8edf8e51 (do not edit this line) */
