/* Generated By:JJTree: Do not edit this line. ASTSubstitution_assertion.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTSubstitution_assertion extends SimpleNode {
  public ASTSubstitution_assertion(int id) {
    super(id);
  }

  public ASTSubstitution_assertion(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c26e15d1d038692cb08ca8950dd4265f (do not edit this line) */
