/* Generated By:JJTree: Do not edit this line. ASTSous_ensembles_finis.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTSous_ensembles_finis extends SimpleNode {
  public ASTSous_ensembles_finis(int id) {
    super(id);
  }

  public ASTSous_ensembles_finis(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2acdf56b8a8eea78857725775dd8c748 (do not edit this line) */
