/* Generated By:JJTree: Do not edit this line. ASTSubstitution_simultanee.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTSubstitution_simultanee extends SimpleNode {
  public ASTSubstitution_simultanee(int id) {
    super(id);
  }

  public ASTSubstitution_simultanee(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f3ce5576a3f152cccc06a09037d4ee8f (do not edit this line) */
