/* Generated By:JJTree: Do not edit this line. ASTSubstitution_binaire.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTSubstitution_binaire extends SimpleNode {
  public ASTSubstitution_binaire(int id) {
    super(id);
  }

  public ASTSubstitution_binaire(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f8b0e49ae94fd60610983dd98a1efb48 (do not edit this line) */
