/* Generated By:JJTree: Do not edit this line. ASTSous_arbre_noeud.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTSous_arbre_noeud extends SimpleNode {
  public ASTSous_arbre_noeud(int id) {
    super(id);
  }

  public ASTSous_arbre_noeud(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=caef8e25d267b55dbc8c1d7ff5dea5cd (do not edit this line) */
