/* Generated By:JJTree: Do not edit this line. ASTSurjection_totale.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTSurjection_totale extends SimpleNode {
  public ASTSurjection_totale(int id) {
    super(id);
  }

  public ASTSurjection_totale(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=083bcf27228f9ddf3407c72e0e5f4799 (do not edit this line) */
