/* Generated By:JJTree: Do not edit this line. ASTSubstitution_devient_tel_que.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTSubstitution_devient_tel_que extends SimpleNode {
  public ASTSubstitution_devient_tel_que(int id) {
    super(id);
  }

  public ASTSubstitution_devient_tel_que(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=38976f8689f2c9ddd2ec18f2d4519bfb (do not edit this line) */
