/* Generated By:JJTree: Do not edit this line. ASTSoustraction_domaine.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTSoustraction_domaine extends SimpleNode {
  public ASTSoustraction_domaine(int id) {
    super(id);
  }

  public ASTSoustraction_domaine(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1d5f02e34928c52f0d6435683176d972 (do not edit this line) */
