/* Generated By:JJTree: Do not edit this line. ASTSubstitution_corps_operation.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTSubstitution_corps_operation extends SimpleNode {
  public ASTSubstitution_corps_operation(int id) {
    super(id);
  }

  public ASTSubstitution_corps_operation(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6199696de3c865dbd6e7df25f2dc8cc1 (do not edit this line) */
