/* Generated By:JJTree: Do not edit this line. ASTSubstitution_devient_egal.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTSubstitution_devient_egal extends SimpleNode {
  public ASTSubstitution_devient_egal(int id) {
    super(id);
  }

  public ASTSubstitution_devient_egal(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e09b4bc3a957dc8077aba03d6e19cd89 (do not edit this line) */
