/* Generated By:JJTree: Do not edit this line. ASTSubstitution_bloc.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTSubstitution_bloc extends SimpleNode {
  public ASTSubstitution_bloc(int id) {
    super(id);
  }

  public ASTSubstitution_bloc(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5144dd8bf381f4a95a6419713039b19e (do not edit this line) */
