/* Generated By:JJTree: Do not edit this line. ASTSubstitution_sequence.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTSubstitution_sequence extends SimpleNode {
  public ASTSubstitution_sequence(int id) {
    super(id);
  }

  public ASTSubstitution_sequence(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b96bc6ceb618421dd7aefbea917b7f49 (do not edit this line) */
