/* Generated By:JJTree: Do not edit this line. ASTSubstitution_bloc.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTSubstitution_bloc extends SimpleNode {
  public ASTSubstitution_bloc(int id) {
    super(id);
  }

  public ASTSubstitution_bloc(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8785f4c450cfe400dc2e87a8cc476f13 (do not edit this line) */
