/* Generated By:JJTree: Do not edit this line. ASTSubstitution_variable_locale.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTSubstitution_variable_locale extends SimpleNode {
  public ASTSubstitution_variable_locale(int id) {
    super(id);
  }

  public ASTSubstitution_variable_locale(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=fcb27bebd718da76107e81c640d4cb2e (do not edit this line) */
