/* Generated By:JJTree: Do not edit this line. ASTSubstitution_tant_que.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTSubstitution_tant_que extends SimpleNode {
  public ASTSubstitution_tant_que(int id) {
    super(id);
  }

  public ASTSubstitution_tant_que(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5ea579fcdb92b482e3d44f7a8bf9aba6 (do not edit this line) */
