/* Generated By:JJTree: Do not edit this line. ASTSous_arbre_gauche.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTSous_arbre_gauche extends SimpleNode {
  public ASTSous_arbre_gauche(int id) {
    super(id);
  }

  public ASTSous_arbre_gauche(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=14586b4731ac71e0716a970839507ed2 (do not edit this line) */
