/* Generated By:JJTree: Do not edit this line. ASTSubstitution_choix_borne.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTSubstitution_choix_borne extends SimpleNode {
  public ASTSubstitution_choix_borne(int id) {
    super(id);
  }

  public ASTSubstitution_choix_borne(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=71534cd5939860b0733c2ca7f93962c7 (do not edit this line) */
