/* Generated By:JJTree: Do not edit this line. ASTSurjection_partielle.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTSurjection_partielle extends SimpleNode {
  public ASTSurjection_partielle(int id) {
    super(id);
  }

  public ASTSurjection_partielle(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b7504fb2657d0fa350a79f3f4056688e (do not edit this line) */
