/* Generated By:JJTree: Do not edit this line. ASTTete_suite.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTTete_suite extends SimpleNode {
  public ASTTete_suite(int id) {
    super(id);
  }

  public ASTTete_suite(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b5e7e6d0e29c90e4f8a4741bf1d07ae5 (do not edit this line) */
