/* Generated By:JJTree: Do not edit this line. ASTTermeSimple.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTTermeSimple extends SimpleNode {
  public ASTTermeSimple(int id) {
    super(id);
  }

  public ASTTermeSimple(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a38611f4241d02ad31ee4f4c54c987ab (do not edit this line) */
