/* Generated By:JJTree: Do not edit this line. ASTTransformee_fonction.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTTransformee_fonction extends SimpleNode {
  public ASTTransformee_fonction(int id) {
    super(id);
  }

  public ASTTransformee_fonction(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7380241d709d627fc50d9f9ae98cd0e0 (do not edit this line) */
