/* Generated By:JJTree: Do not edit this line. ASTTransformee_relation.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTTransformee_relation extends SimpleNode {
  public ASTTransformee_relation(int id) {
    super(id);
  }

  public ASTTransformee_relation(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=93662a3cbc4944583f973ea9314a7648 (do not edit this line) */
