/* Generated By:JJTree: Do not edit this line. ASTTerme_record.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTTerme_record extends SimpleNode {
  public ASTTerme_record(int id) {
    super(id);
  }

  public ASTTerme_record(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b31adbaa5956cc14d48f46fe7018d653 (do not edit this line) */
