/* Generated By:JJTree: Do not edit this line. ASTUnion_generalisee.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaire;

public
class ASTUnion_generalisee extends SimpleNode {
  public ASTUnion_generalisee(int id) {
    super(id);
  }

  public ASTUnion_generalisee(ParserB p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserBVisitor visitor, Object data) throws ParserBException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3e3226441603027346a778f60f97aae0 (do not edit this line) */
