/* Generated By:JavaCC: Do not edit this line. ParserBTreeConstants.java Version 5.0 */
package grammaire;

public interface ParserBTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTIDENT_REN = 2;
  public int JJTMACHINE = 3;
  public int JJTENTETE = 4;
  public int JJTCONSTRAINTS = 5;
  public int JJTSETS = 6;
  public int JJTENSEMBLE = 7;
  public int JJTCONCRETECONSTANTS = 8;
  public int JJTABSTRACTCONSTANTS = 9;
  public int JJTPROPERTIES = 10;
  public int JJTVALUES = 11;
  public int JJTVALUE = 12;
  public int JJTCONCRETEVARIABLES = 13;
  public int JJTABSTRACTVARIABLES = 14;
  public int JJTINVARIANT = 15;
  public int JJTINITIALISATION = 16;
  public int JJTOPERATIONS = 17;
  public int JJTOPERATION = 18;
  public int JJTENTETEOPERATION = 19;
  public int JJTTERME = 20;
  public int JJTTERMESIMPLE = 21;
  public int JJTENTIER_LIT = 22;
  public int JJTBOOLEAN_LIT = 23;
  public int JJTTERME_RECORD = 24;
  public int JJTEXPR_TABLEAU = 25;
  public int JJTCONDITION = 26;
  public int JJTINSTRUCTION = 27;
  public int JJTINSTRUCTION_CORPS_OPERATION = 28;
  public int JJTINSTRUCTION_BLOC = 29;
  public int JJTINSTRUCITON_VARIABLE_LOCALE = 30;
  public int JJTINSTRUCTION_DEVIENT_EGAL = 31;
  public int JJTINSTRUCTION_APPEL_OPERATION = 32;
  public int JJTINSTRUCTION_SEQUENCE = 33;
  public int JJTINSTRUCTION_CONDITIONNELLE = 34;
  public int JJTINSTRUCTION_CAS = 35;
  public int JJTSUBSTITUTION_TANT_QUE = 36;
  public int JJTINSTRUCTION_ASSERTION = 37;
  public int JJTPREDICAT = 38;
  public int JJTPREDICAT_PARENTHESE = 39;
  public int JJTPREDICAT_NEGATION = 40;
  public int JJTPREDICAT_UNIVERSEL = 41;
  public int JJTPREDICAT_EXISTENTIEL = 42;
  public int JJTPREDICAT_EGALITE = 43;
  public int JJTPREDICAT_INEGALITE = 44;
  public int JJTPREDICAT_APPARTENANCE = 45;
  public int JJTPREDICAT_NOT_APPARTENANCE = 46;
  public int JJTPREDICAT_INCLUSION = 47;
  public int JJTPREDICAT_INSCLUSION_STRICTE = 48;
  public int JJTPREDICAT_NON_INCLUSION = 49;
  public int JJTPREDICAT_NON_INCLUSION_STRICTE = 50;
  public int JJTPREDICAT_INFERIEUR_OU_EGAL = 51;
  public int JJTPREDICAT_STRICTEMENT_INFERIEUR = 52;
  public int JJTPREDICAT_STRICTEMENT_SUPERIEUR = 53;
  public int JJTPREDICAT_SUPERIEUR_OU_EGAL = 54;
  public int JJTEXPRESSION = 55;
  public int JJTEXPRESSION_PRIMAIRE = 56;
  public int JJTEXPRESSION_BOOLEENNE = 57;
  public int JJTEXPRARITH = 58;
  public int JJTEXPRESSION_D_ENSEMBLES = 59;
  public int JJTCONSTRUCTION_D_ENSEMBLES = 60;
  public int JJTCONSTRUCTION_DE_FONCTIONS = 61;
  public int JJTEXPRESSION_DE_RELATIONS = 62;
  public int JJTEXPR_PARENTHESEE = 63;
  public int JJTCONVERSION_BOOL = 64;
  public int JJTENSEMBLE_VIDE = 65;
  public int JJTENSEMBLE_ENTIER = 66;
  public int JJTENSEMBLE_CHAINES = 67;
  public int JJTENSEMBLE_BOOLEEN = 68;
  public int JJTSOUS_ENSEMBLES = 69;
  public int JJTSOUS_ENSEMBLES_FINIS = 70;
  public int JJTSUBSTITUTION = 71;
  public int JJTSUBSTITUTION_CORPS_OPERATION = 72;
  public int JJTSUBSTITUTION_BLOC = 73;
  public int JJTSUBSTITUTION_IDENTITE = 74;
  public int JJTSUBSTITUTION_DEVIENT_EGAL = 75;
  public int JJTSUBSTITUTION_PRECONDITION = 76;
  public int JJTSUBSTITUTION_ASSERTION = 77;
  public int JJTSUBSTITUTION_CHOIX_BORNE = 78;
  public int JJTSUBSTITUTION_CONDITIONNELLE = 79;
  public int JJTSUBSTITUTION_SELECTION = 80;
  public int JJTSUBSTITUTION_CAS = 81;
  public int JJTSUBSTITUTION_CHOIX_NON_BORNE = 82;
  public int JJTSUBSTITUTION_DEFINITION_LOCALE = 83;
  public int JJTSUBSTITUTION_DEVIENT_ELT_DE = 84;
  public int JJTSUBSTITUTION_DEVIENT_TEL_QUE = 85;
  public int JJTSUBSTITUTION_VARIABLE_LOCALE = 86;
  public int JJTSUBSTITUTION_APPEL_OPERATION = 87;
  public int JJTLISTE_IDENT = 88;
  public int JJTENSEMBLE_SIMPLE = 89;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Ident_ren",
    "Machine",
    "EnTete",
    "Constraints",
    "Sets",
    "Ensemble",
    "ConcreteConstants",
    "AbstractConstants",
    "Properties",
    "Values",
    "Value",
    "ConcreteVariables",
    "AbstractVariables",
    "Invariant",
    "Initialisation",
    "Operations",
    "Operation",
    "EnteteOperation",
    "Terme",
    "TermeSimple",
    "Entier_Lit",
    "Boolean_Lit",
    "Terme_record",
    "Expr_tableau",
    "Condition",
    "Instruction",
    "Instruction_corps_operation",
    "Instruction_bloc",
    "Instruciton_variable_locale",
    "Instruction_devient_egal",
    "Instruction_appel_operation",
    "Instruction_sequence",
    "Instruction_conditionnelle",
    "Instruction_cas",
    "Substitution_tant_que",
    "Instruction_assertion",
    "predicat",
    "Predicat_parenthese",
    "Predicat_Negation",
    "Predicat_Universel",
    "Predicat_Existentiel",
    "Predicat_Egalite",
    "Predicat_Inegalite",
    "Predicat_Appartenance",
    "Predicat_Not_Appartenance",
    "Predicat_Inclusion",
    "Predicat_Insclusion_Stricte",
    "Predicat_Non_Inclusion",
    "Predicat_Non_Inclusion_Stricte",
    "Predicat_Inferieur_Ou_Egal",
    "Predicat_Strictement_Inferieur",
    "Predicat_Strictement_Superieur",
    "Predicat_Superieur_Ou_Egal",
    "Expression",
    "Expression_primaire",
    "Expression_booleenne",
    "ExprArith",
    "Expression_d_ensembles",
    "Construction_d_ensembles",
    "Construction_de_fonctions",
    "Expression_de_relations",
    "Expr_parenthesee",
    "Conversion_bool",
    "Ensemble_vide",
    "Ensemble_entier",
    "Ensemble_chaines",
    "Ensemble_booleen",
    "Sous_ensembles",
    "Sous_ensembles_finis",
    "Substitution",
    "Substitution_corps_operation",
    "Substitution_bloc",
    "Substitution_identite",
    "Substitution_devient_egal",
    "Substitution_precondition",
    "Substitution_assertion",
    "Substitution_choix_borne",
    "Substitution_conditionnelle",
    "Substitution_selection",
    "Substitution_cas",
    "Substitution_choix_non_borne",
    "Substitution_definition_locale",
    "Substitution_devient_elt_de",
    "Substitution_devient_tel_que",
    "Substitution_variable_locale",
    "Substitution_appel_operation",
    "Liste_ident",
    "Ensemble_simple",
  };
}
/* JavaCC - OriginalChecksum=1751b13b1f418c6e2736c3620351c43e (do not edit this line) */
