/* Generated By:JavaCC: Do not edit this line. ParserBTreeConstants.java Version 6.0_1 */
package grammaire;

public interface ParserBTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTIDENT_REN = 2;
  public int JJTMACHINE = 3;
  public int JJTENTETE = 4;
  public int JJTCONSTRAINTS = 5;
  public int JJTSETS = 6;
  public int JJTENSEMBLE = 7;
  public int JJTCONCRETECONSTANTS = 8;
  public int JJTABSTRACTCONSTANTS = 9;
  public int JJTPROPERTIES = 10;
  public int JJTVALUES = 11;
  public int JJTVALUE = 12;
  public int JJTCONCRETEVARIABLES = 13;
  public int JJTABSTRACTVARIABLES = 14;
  public int JJTINVARIANT = 15;
  public int JJTINITIALISATION = 16;
  public int JJTOPERATIONS = 17;
  public int JJTOPERATION = 18;
  public int JJTENTETEOPERATION = 19;
  public int JJTTERME = 20;
  public int JJTTERMESIMPLE = 21;
  public int JJTENTIER_LIT = 22;
  public int JJTBOOLEAN_LIT = 23;
  public int JJTTERME_RECORD = 24;
  public int JJTEXPR_TABLEAU = 25;
  public int JJTCONDITION = 26;
  public int JJTEQUAL = 27;
  public int JJTNOTEQUAL = 28;
  public int JJTLESSTHAN = 29;
  public int JJTGREATHERTHAN = 30;
  public int JJTLESSTHANOREQUAL = 31;
  public int JJTGREATHERTHANOREQUAL = 32;
  public int JJTNOT = 33;
  public int JJTAND = 34;
  public int JJTOR = 35;
  public int JJTINSTRUCTION = 36;
  public int JJTINSTRUCTION_CORPS_OPERATION = 37;
  public int JJTINSTRUCTION_BLOC = 38;
  public int JJTINSTRUCITON_VARIABLE_LOCALE = 39;
  public int JJTINSTRUCTION_DEVIENT_EGAL = 40;
  public int JJTINSTRUCTION_APPEL_OPERATION = 41;
  public int JJTINSTRUCTION_SEQUENCE = 42;
  public int JJTINSTRUCTION_CONDITIONNELLE = 43;
  public int JJTINSTRUCTION_CAS = 44;
  public int JJTSUBSTITUTION_TANT_QUE = 45;
  public int JJTINSTRUCTION_ASSERTION = 46;
  public int JJTPREDICAT = 47;
  public int JJTUNION = 48;
  public int JJTIMPLICATION = 49;
  public int JJTEQUIVALENCE = 50;
  public int JJTPREDICAT_PARENTHESE = 51;
  public int JJTPREDICAT_NEGATION = 52;
  public int JJTPREDICAT_UNIVERSEL = 53;
  public int JJTPREDICAT_EXISTENTIEL = 54;
  public int JJTPREDICAT_EGALITE = 55;
  public int JJTPREDICAT_INEGALITE = 56;
  public int JJTPREDICAT_APPARTENANCE = 57;
  public int JJTPREDICAT_NOT_APPARTENANCE = 58;
  public int JJTPREDICAT_INCLUSION = 59;
  public int JJTPREDICAT_INSCLUSION_STRICTE = 60;
  public int JJTPREDICAT_NON_INCLUSION = 61;
  public int JJTPREDICAT_NON_INCLUSION_STRICTE = 62;
  public int JJTPREDICAT_INFERIEUR_OU_EGAL = 63;
  public int JJTPREDICAT_STRICTEMENT_INFERIEUR = 64;
  public int JJTPREDICAT_STRICTEMENT_SUPERIEUR = 65;
  public int JJTPREDICAT_SUPERIEUR_OU_EGAL = 66;
  public int JJTEXPRESSION = 67;
  public int JJTFONCTION_PARTIELLE = 68;
  public int JJTFONCTION_TOTALE = 69;
  public int JJTINJECTION_PARTIELLE = 70;
  public int JJTINJECTION_TOTALE = 71;
  public int JJTSURJECTION_PARTIELLE = 72;
  public int JJTSURJECTION_TOTALE = 73;
  public int JJTBIJECTION_TOTALE = 74;
  public int JJTCOUPLE = 75;
  public int JJTEXPRESSION_PRIMAIRE = 76;
  public int JJTEXPRESSION_BOOLEENNE = 77;
  public int JJTEXPRARITH = 78;
  public int JJTMOINSUNAIRE = 79;
  public int JJTSUCCESSEUR = 80;
  public int JJTPREDECESSEUR = 81;
  public int JJTMAXIMUM = 82;
  public int JJTMINIMUM = 83;
  public int JJTCARDINAL = 84;
  public int JJTSOMME_GENERALISEE = 85;
  public int JJTPRODUIT_GENERALISEE = 86;
  public int JJTADDITION = 87;
  public int JJTSOUSTRACTION = 88;
  public int JJTPRODUCION = 89;
  public int JJTDIVISION = 90;
  public int JJTMODULO = 91;
  public int JJTPUISSANCE = 92;
  public int JJTEXPRESSION_D_ENSEMBLES = 93;
  public int JJTCONSTRUCTION_D_ENSEMBLES = 94;
  public int JJTENSCOMPREHENSION = 95;
  public int JJTUNION_GENERALISEE = 96;
  public int JJTINTERSECTION_GENERALISEE = 97;
  public int JJTUNION_QUANTIFIEE = 98;
  public int JJTINTERSECTION_QUANTIFIEE = 99;
  public int JJTPRODUIT_ENSEMBLE = 100;
  public int JJTINTERVALLE = 101;
  public int JJTINTERSECTION = 102;
  public int JJTCONSTRUCTION_DE_FONCTIONS = 103;
  public int JJTLAMBDA_EXPRESSION = 104;
  public int JJTENS_COMPREHENSION = 105;
  public int JJTTRANSFORMEE_FONCTION = 106;
  public int JJTTRANSFORMEE_RELATION = 107;
  public int JJTEVALUATION_FONCTION = 108;
  public int JJTEXPRESSION_DE_RELATIONS = 109;
  public int JJTIDENTITE = 110;
  public int JJTPREMIERE_PROJECTION = 111;
  public int JJTDEUXIEME_PROJECTION = 112;
  public int JJTDOMAINE = 113;
  public int JJTCODOMAINE = 114;
  public int JJTENSEMBLERELATION = 115;
  public int JJTCOMPOSITION = 116;
  public int JJTPRODUIT_DIRECT = 117;
  public int JJTPRODUIT_PARALLELE = 118;
  public int JJTRESTRICTION_DOMAINE = 119;
  public int JJTSOUSTRACTIONS_DOMAINE = 120;
  public int JJTRESTRICTION_CODOMAINE = 121;
  public int JJTSOUSTRACTIONS_CODOMAINE = 122;
  public int JJTSURCHARGE = 123;
  public int JJTEXPR_PARENTHESEE = 124;
  public int JJTCONVERSION_BOOL = 125;
  public int JJTENSEMBLE_VIDE = 126;
  public int JJTENSEMBLE_ENTIER = 127;
  public int JJTENSEMBLE_CHAINES = 128;
  public int JJTENSEMBLE_BOOLEEN = 129;
  public int JJTSOUS_ENSEMBLES = 130;
  public int JJTSOUS_ENSEMBLES_FINIS = 131;
  public int JJTSUBSTITUTION = 132;
  public int JJTSUBSTITUTION_SEQUENCE = 133;
  public int JJTSUBSTITUTION_SIMULTANEE = 134;
  public int JJTSUBSTITUTION_CORPS_OPERATION = 135;
  public int JJTSUBSTITUTION_BLOC = 136;
  public int JJTSUBSTITUTION_IDENTITE = 137;
  public int JJTSUBSTITUTION_DEVIENT_EGAL = 138;
  public int JJTSUBSTITUTION_PRECONDITION = 139;
  public int JJTSUBSTITUTION_ASSERTION = 140;
  public int JJTSUBSTITUTION_CHOIX_BORNE = 141;
  public int JJTSUBSTITUTION_CONDITIONNELLE = 142;
  public int JJTSUBSTITUTION_SELECTION = 143;
  public int JJTSUBSTITUTION_CAS = 144;
  public int JJTSUBSTITUTION_CHOIX_NON_BORNE = 145;
  public int JJTSUBSTITUTION_DEFINITION_LOCALE = 146;
  public int JJTSUBSTITUTION_DEVIENT_ELT_DE = 147;
  public int JJTSUBSTITUTION_DEVIENT_TEL_QUE = 148;
  public int JJTSUBSTITUTION_VARIABLE_LOCALE = 149;
  public int JJTSUBSTITUTION_APPEL_OPERATION = 150;
  public int JJTLISTE_IDENT = 151;
  public int JJTENSEMBLE_SIMPLE = 152;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Ident_ren",
    "Machine",
    "EnTete",
    "Constraints",
    "Sets",
    "Ensemble",
    "ConcreteConstants",
    "AbstractConstants",
    "Properties",
    "Values",
    "Value",
    "ConcreteVariables",
    "AbstractVariables",
    "Invariant",
    "Initialisation",
    "Operations",
    "Operation",
    "EnteteOperation",
    "Terme",
    "TermeSimple",
    "Entier_Lit",
    "Boolean_Lit",
    "Terme_record",
    "Expr_tableau",
    "Condition",
    "Equal",
    "NotEqual",
    "LessThan",
    "GreatherThan",
    "LessThanOrEqual",
    "GreatherThanOrEqual",
    "Not",
    "And",
    "Or",
    "Instruction",
    "Instruction_corps_operation",
    "Instruction_bloc",
    "Instruciton_variable_locale",
    "Instruction_devient_egal",
    "Instruction_appel_operation",
    "Instruction_sequence",
    "Instruction_conditionnelle",
    "Instruction_cas",
    "Substitution_tant_que",
    "Instruction_assertion",
    "predicat",
    "Union",
    "Implication",
    "Equivalence",
    "Predicat_parenthese",
    "Predicat_Negation",
    "Predicat_Universel",
    "Predicat_Existentiel",
    "Predicat_Egalite",
    "Predicat_Inegalite",
    "Predicat_Appartenance",
    "Predicat_Not_Appartenance",
    "Predicat_Inclusion",
    "Predicat_Insclusion_Stricte",
    "Predicat_Non_Inclusion",
    "Predicat_Non_Inclusion_Stricte",
    "Predicat_Inferieur_Ou_Egal",
    "Predicat_Strictement_Inferieur",
    "Predicat_Strictement_Superieur",
    "Predicat_Superieur_Ou_Egal",
    "Expression",
    "Fonction_partielle",
    "Fonction_totale",
    "Injection_partielle",
    "Injection_totale",
    "Surjection_partielle",
    "Surjection_totale",
    "Bijection_totale",
    "Couple",
    "Expression_primaire",
    "Expression_booleenne",
    "ExprArith",
    "MoinsUnaire",
    "Successeur",
    "Predecesseur",
    "Maximum",
    "Minimum",
    "Cardinal",
    "Somme_generalisee",
    "Produit_generalisee",
    "Addition",
    "Soustraction",
    "Producion",
    "Division",
    "Modulo",
    "Puissance",
    "Expression_d_ensembles",
    "Construction_d_ensembles",
    "EnsComprehension",
    "Union_generalisee",
    "Intersection_generalisee",
    "Union_quantifiee",
    "Intersection_quantifiee",
    "Produit_ensemble",
    "Intervalle",
    "Intersection",
    "Construction_de_fonctions",
    "Lambda_expression",
    "Ens_comprehension",
    "Transformee_fonction",
    "Transformee_relation",
    "Evaluation_fonction",
    "Expression_de_relations",
    "Identite",
    "Premiere_projection",
    "Deuxieme_projection",
    "Domaine",
    "Codomaine",
    "EnsembleRelation",
    "Composition",
    "Produit_direct",
    "Produit_parallele",
    "Restriction_domaine",
    "Soustractions_domaine",
    "Restriction_codomaine",
    "Soustractions_codomaine",
    "Surcharge",
    "Expr_parenthesee",
    "Conversion_bool",
    "Ensemble_vide",
    "Ensemble_entier",
    "Ensemble_chaines",
    "Ensemble_booleen",
    "Sous_ensembles",
    "Sous_ensembles_finis",
    "Substitution",
    "Substitution_sequence",
    "Substitution_simultanee",
    "Substitution_corps_operation",
    "Substitution_bloc",
    "Substitution_identite",
    "Substitution_devient_egal",
    "Substitution_precondition",
    "Substitution_assertion",
    "Substitution_choix_borne",
    "Substitution_conditionnelle",
    "Substitution_selection",
    "Substitution_cas",
    "Substitution_choix_non_borne",
    "Substitution_definition_locale",
    "Substitution_devient_elt_de",
    "Substitution_devient_tel_que",
    "Substitution_variable_locale",
    "Substitution_appel_operation",
    "Liste_ident",
    "Ensemble_simple",
  };
}
/* JavaCC - OriginalChecksum=e0f4ec7a21bf3f881eaab8e3e54bf766 (do not edit this line) */
